lcoin_wallet/main/routes.py
from flask import render_template, url_for, redirect
from lcoin_wallet.main.utils import (
    check_if_pending, get_transactions, transaction_html_constructor, get_btc_price)
from flask_login import login_required, current_user
from flask import Blueprint, send_from_directory


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@login_required
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    exists, _ = check_if_pending(current_user)
    transactions = get_transactions(current_user)
    btc_price = round(get_btc_price(), 6)
    transactions_html = transaction_html_constructor(transactions, btc_price)
    
    if exists[1] is True:
        notification = "badge1"
    else:
        notification = None

    image_file = url_for('main.profile_photo')

    if len(transactions) > 0:
        return render_template("index.html", title='Wallet', image_file=image_file, notification=notification, transactions_html=transactions_html, btc_price=btc_price)
    else:
        return render_template("index.html", title='Wallet', image_file=image_file, notification=notification, transactions=[], btc_price=btc_price)


@main.route('/sw.js')
def sw():
    return send_from_directory('static', 'sw.js')


@main.route('/manifest.json')
def manifest():
    return send_from_directory('static', 'manifest.json')


@main.route('/app/static/js')
def app_js():
    return send_from_directory('static', 'javascript/app.js')


@main.route('/l-coin-logo.png')
def logo():
    return send_from_directory('static', 'images/l-coin-logo.png')


@main.route('/profile_photo')
def profile_photo():
    return send_from_directory('static', f'profile_pics/{current_user.image_file}')


@main.route('/error_500')
def error_500():
    error = "Internal server error has been detected...Internal server error has been detected...Internal server"
    return render_template("errors/500.html", e=error)

lcoin_wallet/users/routes.py
import os
from sqlalchemy import func

from lcoin_wallet import db, bcrypt
from lcoin_wallet.models import User, Transaction
from lcoin_wallet.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                      RequestResetForm,
                                      ResetPasswordForm)

from flask import (render_template, url_for, flash,
                   redirect, request, Blueprint, current_app)
import flask

from lcoin_wallet.models import User, Transaction, EmailWhitelist

from flask_login import login_required, login_user, current_user, logout_user

from lcoin_wallet.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            prev_picture = os.path.join(
                current_app.root_path, 'static/profile_pics', current_user.image_file)
            if os.path.exists(prev_picture) and current_user.image_file != "default.jpeg":
                os.remove(prev_picture)
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        if current_user.username != form.username.data:
            transactions_by = Transaction.query.filter_by(
                by=current_user.username)

            for transaction in transactions_by:
                transaction.by = form.username.data

            transactions_to = Transaction.query.filter_by(
                to=current_user.username)

            for transaction in transactions_to:
                transaction.to = form.username.data

            db.session.commit()

        current_user.username = form.username.data

        if EmailWhitelist.query.filter(func.lower(User.email) == func.lower(form.email.data)).first():
            current_user.email = form.email.data

        db.session.commit()

        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))

    elif flask.request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)

    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    new_user_exists = User.query.filter(func.lower(User.username) == func.lower(
        form.username.data), func.lower(User.email) == func.lower(form.email.data)).first()
    if new_user_exists:
        flash(
            f'Welcome {new_user_exists.username}! Looks like you are already registered, please log in!', 'success')
        return redirect(url_for('users.login'))

    if form.validate_on_submit():
        whitelist_entry = EmailWhitelist.query.filter_by(email=form.email.data).first()
        if whitelist_entry:
            hashed_passoword = bcrypt.generate_password_hash(
                form.password.data).decode('utf-8')
            
            user = User(username=form.username.data,
                        email=form.email.data, password=hashed_passoword, balance=whitelist_entry.initial_balance)
            
            transaction = Transaction(by="LCoin",
                                      to=form.username.data,
                                      amount=whitelist_entry.initial_balance,
                                      concept="Welcome to LCoin, here is the balance you had in the last marketplace!")
            db.session.add(user)
            db.session.add(transaction)
            db.session.commit()
            flash(
                f'Welcome {user.username}! You can now use your credentials to log in.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash(
                f'Sorry but that email is not in our list!', 'danger')

    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(func.lower(User.username) == func.lower(
            form.email_or_username.data)).first()
        if not user:
            user = User.query.filter(func.lower(User.email) == func.lower(
                form.email_or_username.data)).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            try:
                next_page = request.args.get('next')
            except AttributeError:
                next_page = None

            flash(f'Welcome {user.username}!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login unsuccessfull, please check email and password...', 'danger')

    return render_template("login.html", title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/reset_password',  methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            f'An email has been sent to {form.email.data} with instructions to reset your password!', 'success')
        return redirect(url_for('users.login'))

    return render_template("reset_request.html", title='Reset Password', form=form)


@users.route('/reset_password/<token>',  methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)

    if not user:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_passoword = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')

        user.password = hashed_passoword

        db.session.commit()

        flash(
            f'{user.username}, your password has been reset successfully!', 'success')
        return redirect(url_for('main.home'))

    return render_template("users.reset_token.html", title='Reset Password', form=form)

lcoin_wallet/templates/account.html
{% extends "layout.html" %}
{% block content %}
<body class="background">
   
   <div class="flex-container">
      <div class="flex-child" style="margin-left: 3%;">
         <p class="wallet" style="margin-bottom:40px; margin-top:40px;">Account</p>
      </div>
      <div class="flex-child" style="text-align:right; margin-right: 10%;">
         <p class="done" style="margin-bottom:40px;"><a href="{{url_for('main.home')}}" style="color: #f9a241;">⨉</a></p>
      </div>
   </div>

   <div class="wallet-holder">
      <div class="flex-container">
         <div class="flex-child" style="width: 50px; margin-left: 3%; padding-top: 5px; padding-bottom: 10px;">
            <img class="round_icon float-left" src="{{ image_file }}" width="60" height="60"></img>
         </div>
         <div class="flex-child">
            <p class="bold_text" style="font-size: 170%">{{ current_user.username }}</p>
            <p class="subtext" style="font-size: 75%; padding-top: 10px; padding-bottom: 10px;">
               {{current_user.email}}
            </p>
         </div>
      </div>
   </div>
   <p class="dark-text" style="font-size: 90%; margin-left: 5%; margin-top: 35px; margin-bottom: 40px;">Update Account
   </p>
   <fieldset class="form-group">
      <div class="wallet-holder">
         <div class="form-container">
            <form method="POST" action="" enctype="multipart/form-data">
               {{ form.hidden_tag() }}
               <div class="form-group">
                  {{ form.username.label(class="dark-text-form-top") }}
                  {% if form.username.errors %}
                  {{ form.username(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                     {% for error in form.username.errors %}
                     <span class="error-text">{{ error }}</span>
                     {% endfor %}
                  </div>
                  {% else %}
                  {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
               </div>
               <div class="form-group">
                  {{ form.email.label(class="dark-text-form") }}
                  {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                     {% for error in form.email.errors %}
                     <span class="error-text">{{ error }}</span>
                     {% endfor %}
                  </div>
                  {% else %}
                  {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
               </div>
               <div class="form-group">
                  {{ form.picture.label(class="dark-text-form") }}
                  {{ form.picture(class="dark-text-form-file ") }}
                  {% if form.picture.errors %}
                  {% for error in form.picture.errors %}
                  <span class="text-danger">{{ error }}</span><br>
                  {% endfor %}
                  {% endif %}
               </div>
               <div style="text-align: center;  margin-bottom: -10px; margin-top: -30px; width: 100%;  ">
                  <div class="form-group">{{ form.submit(class="button-submit button") }}</div>
                  </div>
                  </form>
               </fieldset>
   
         </div>
      </div>
   </div>
   <div style="text-align: center;  width: 100%; padding-right:3%; ">
      <div class="" ><button onclick="location.href='{{url_for('users.logout')}}'"
      class="button" style="width:33%;">Log out</button></div>
   </div>
       <!-- Start of HubSpot Embed Code -->
       <script
       type="text/javascript"
       id="hs-script-loader"
       async
       defer
       src="//js-eu1.hs-scripts.com/25879453.js"
     ></script>
     <!-- End of HubSpot Embed Code -->
</body>
{% endblock content %}

lcoin_wallet/templates/index.html
{% extends "layout.html" %}
{% block content %}
<body class="background">
   <p class="wallet", style="margin-bottom:40px; margin-top:40px;">Wallet</p>
   <div class="wallet-holder">
      <div class="flex-container">
         <div class="flex-child">
            <p class="bold_text" style="font-size: 170%">₺{{ current_user.balance | round(4)}}</p>
            <p class="subtext" style="font-size: 75%; padding-top: 10px; padding-bottom: 3px;">{{ (btc_price * current_user.balance) | round(5) }} BTC</p>
         </div>
         <div class="flex-child" style="text-align: right; margin-top: 12px">
            <img class="lcoin_icon"
               src="{{ image_file }}"
               width="40" height="40">
         </div>
      </div>
      <table class="button-holder" style="margin-left: 4%;">
         <tr>
            <td><button onclick="location.href='{{url_for('transactions.send')}}'" class="button"><span class="text">↑ Send</a></span></button></td>
            <td><button onclick="location.href='{{url_for('transactions.request')}}'" id="notify" class="button {{ notification }}" data-badge="" style="margin-left: 20px;"><span class="text">↓ Request</span></button></td>
            <td><button onclick="location.href='{{url_for('users.account')}}'" class="button" style="margin-left: 20px;"><span class="text">⚙ </span></button></td>
         </tr>
      </table>
      <div class="flex-container">
         <div class="flex-child">
            <p class="dark-text" style="font-size: 90%; margin-left: 8%;">Holdings:</p>
         </div>
         <div class="flex-child" style="text-align: right">
         </div>
      </div>
      <div class="flex-container">
         <div class="" style="margin-left: 4%;">
            <img class="round_icon" style="margin-left: 3%;" src="{{ url_for('main.logo') }}" width="55" height="55">
         </div>
         <div class="flex-child" style="margin-left: 20px;">
            <p class="bold_text" style="margin-left: 0;">Learn Coin</p>
            <p class="dark-text" style="margin-top: -10px; margin-left: 0; font-size: 80%;">LCC</p>
         </div>
         <div class="flex-child" style="text-align: right; margin-bottom: 20px;">
            <p class="bold_text" style="margin-right: 10%;">₺{{ current_user.balance | round(5)}}</p>
            <p class="dark-text" style="margin-top: -10px; margin-right: 10%; font-size: 80%;">{{ (btc_price * current_user.balance) | round(5) }} BTC</p>
         </div>
      </div>
   </div>

   <p class="dark-text" style="font-size: 90%; margin-left: 5%; margin-top: 35px; margin-bottom: 40px;">Transactions</p>
   <div class="wallet-holder">
      <p class="dark-text" style="font-size: 90%; padding-left: 4%; padding-top: 15px; padding-bottom: 5px;">Completed</p>

      {{transactions_html | safe}}

   </div>
       <!-- Start of HubSpot Embed Code -->
       <script
       type="text/javascript"
       id="hs-script-loader"
       async
       defer
       src="//js-eu1.hs-scripts.com/25879453.js"
     ></script>
     <!-- End of HubSpot Embed Code -->
</body>
{% endblock content %}

lcoin_wallet/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta
      http-equiv="Content-Security-Policy"
      content="upgrade-insecure-requests"
    />
    <meta
      http-equiv="Cache-Control"
      content="no-cache, no-store, must-revalidate"
    />

    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <script
      type="text/javascript"
      src="{{url_for('static', filename='javascript/app.js')}}"
    ></script>

    <link
      rel="manifest"
      href="{{url_for('static', filename='manifest.json')}}"
    />

    <meta name="theme-color" content="#000000" />

    <link rel="apple-touch-icon" href="{{url_for('main.logo')}}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />

    <!-- Latest compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.ico') }}"
    />

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='javascript/close-alert.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='javascript/api-accept.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='javascript/api-deny.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='javascript/api-notify.js') }}"
    ></script>

    <script>
      $(function () {
        $('[data-toggle="popover"]').popover();
      });
    </script>

    <!-- Hotjar Tracking Code for https://lcoin.es -->
    <script>
      (function (h, o, t, j, a, r) {
        h.hj =
          h.hj ||
          function () {
            (h.hj.q = h.hj.q || []).push(arguments);
          };
        h._hjSettings = { hjid: 2976070, hjsv: 6 };
        a = o.getElementsByTagName("head")[0];
        r = o.createElement("script");
        r.async = 1;
        r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
        a.appendChild(r);
      })(window, document, "https://static.hotjar.com/c/hotjar-", ".js?sv=");
    </script>

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Learn Coin</title>
    {% endif %}

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  {% with messages = get_flashed_messages(with_categories= true) %} {% if
  messages %} {% for category, message in messages %}
  <div class="alert alert-{{ category }}">
    <button type="button" class="close" data-dismiss="alert">⨉</button>
    {{ message }}
  </div>

  {% endfor %} {% endif %} {% endwith %} {% block content %} {%endblock%}
</html>

lcoin_wallet/templates/login.html
{% extends "layout.html" %} {% block content %}
<body class="background">
  <p class="wallet" , style="margin-bottom:40px; margin-top:40px;">Login</p>

  <fieldset class="form-group">
      <div class="wallet-holder">
          <div class="form-container">
              <form method="POST" action="" enctype="multipart/form-data">
                  {{ form.hidden_tag() }}

                  <div class="form-group">
                      {{ form.email_or_username.label(class="dark-text-form") }}
                      {% if form.email_or_username.errors %}
                      {{ form.email_or_username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email_or_username.errors %}
                          <span class="error-text">{{ error }}</span>
                          {% endfor %}
                      </div>
                      {% else %}
                      {{ form.email_or_username(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group" style="position: relative">
                    {{ form.password.label(class="dark-text-form") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                          <i class="far fa-eye eyeButton" id="togglePassword"></i>
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span class="error-text">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-password form-control form-control-lg", id="password") }}

                          <i class="far fa-eye eyeButton" id="togglePassword"></i>

                    {% endif %}
                    <script type = "text/javascript" src="{{url_for('static', filename='javascript/password-eye.js')}}"></script>  
                </div>
                <div class="flex-container">
                  <div class="flex-child">
                    <div class="form-check">
                      {{form.remember(class="checkmark")}}
                      {{form.remember.label(class="dark-text-form")}}
                    </div>
              </div>
                  <div class="flex-child" style="text-align: right; margin-right: 2%">
                          <div class="border-top pt-3">
                            <small class="text-muted">
                              Need An Account?
                              <a class="ml-2 link" href="{{ url_for('users.register') }}">Sign Up Now</a>
                            </small>
                          </div>
                          <small class="text-muted">
                            <a class="ml-2 link" href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                          </small>
                    </div>
                </div>
                <div class="separator"></div>
          </div>
      </div>

      <div style="margin: 0 auto; width: 100%; text-align:center; margin-top:20px;">
                      <div class="form-group">{{ form.submit(class="button-submit button") }}</div>
      </div>
      </form>
      </fieldset>
  </div>
    <!-- Start of HubSpot Embed Code -->
    <script
      type="text/javascript"
      id="hs-script-loader"
      async
      defer
      src="//js-eu1.hs-scripts.com/25879453.js"
    ></script>
    <!-- End of HubSpot Embed Code -->
</body>
{% endblock content %}

lcoin_wallet/templates/register.html
{% extends "layout.html" %}
{% block content %}
<body class="background">
   <p class="wallet" , style="margin-bottom:40px; margin-top:40px;">Register</p>
   <fieldset class="form-group">
      <div class="wallet-holder">
         <div class="form-container">
            <form method="POST" action="" enctype="multipart/form-data">
               {{ form.hidden_tag() }}
               <div class="form-group">
                  {{ form.username.label(class="dark-text-form") }}
                  {% if form.username.errors %}
                  {{ form.username(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                     {% for error in form.username.errors %}
                     <span class="error-text">{{ error }}</span>
                     {% endfor %}
                  </div>
                  {% else %}
                  {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
               </div>
               <div class="form-group">
                  {{ form.email.label(class="dark-text-form") }}
                  {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                     {% for error in form.email.errors %}
                     <span class="error-text">{{ error }}</span>
                     {% endfor %}
                  </div>
                  {% else %}
                  {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
               </div>
               <div class="form-group" style="position: relative">
                  {{ form.password.label(class="dark-text-form") }}
                  {% if form.password.errors %}
                      {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <i class="far fa-eye eyeButton" id="togglePassword"></i>
                      <div class="invalid-feedback">
                          {% for error in form.password.errors %}
                              <span class="error-text">{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.password(class="form-password form-control form-control-lg", id="password") }}

                        <i class="far fa-eye eyeButton" id="togglePassword"></i>

                  {% endif %}
              </div>
               <div class="form-group">
                  {{ form.confirm_password.label(class="dark-text-form") }}
                  {% if form.confirm_password.errors %}
                  {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                     {% for error in form.confirm_password.errors %}
                     <span class="error-text">{{ error }}</span>
                     {% endfor %}
                  </div>
                  {% else %}
                  {{ form.confirm_password(class="form-control form-control-lg") }}
                  {% endif %}
                  <script type = "text/javascript" src="{{url_for('static', filename='javascript/password-eye.js')}}"></script>
               </div>
               <div class="flex-container">
                  <div class="flex-child" style=" margin-right: 2%">
                     <div class="border-top pt-3">
                        <small class="text-muted">
                        Already Have An Account? <a class="ml-2 link" href="{{ url_for('users.login') }}">Sign In</a>
                        </small>
                     </div>
                  </div>
               </div>
               <div class="separator"></div>
         </div>
      </div>
      <div style="margin: 0 auto; width: 100%; text-align:center; margin-top:20px;">
      <div class="form-group">{{ form.submit(class="button-submit button") }}</div>
      </div>
      </form>
   </fieldset>
   </div>
       <!-- Start of HubSpot Embed Code -->
       <script
       type="text/javascript"
       id="hs-script-loader"
       async
       defer
       src="//js-eu1.hs-scripts.com/25879453.js"
     ></script>
     <!-- End of HubSpot Embed Code -->
</body>
{% endblock content %}

lcoin_wallet/templates/reset_request.html
{% extends "layout.html" %} {% block content %}
<body class="background">
  <p class="wallet" , style="margin-bottom:40px; margin-top:40px;">Reset Password</p>

  <fieldset class="form-group">
      <div class="wallet-holder">
          <div class="form-container">
              <form method="POST" action="" enctype="multipart/form-data">
                  {{ form.hidden_tag() }}

                  <div class="form-group">
                      {{ form.email.label(class="dark-text-form") }}
                      {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                          <span class="error-text">{{ error }}</span>
                          {% endfor %}
                      </div>
                      {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                </div>
                <div class="separator"></div>
          </div>
      </div>

      <div style="margin: 0 auto; width: 100%; text-align:center; margin-top:20px;">
                      <div class="form-group">{{ form.submit(class="button-submit button") }}</div>
      </div>
      </form>
      </fieldset>
  </div>
    <!-- Start of HubSpot Embed Code -->
    <script
      type="text/javascript"
      id="hs-script-loader"
      async
      defer
      src="//js-eu1.hs-scripts.com/25879453.js"
    ></script>
    <!-- End of HubSpot Embed Code -->
</body>
{% endblock content %}